require(httr)
require(methods)
source("starfighter_gm.R")
source("starfighter.R")
args <- commandArgs(TRUE)
## level <- start_level("chock_a_block")
first <- start_level(args[1])
contents_level <- content(first)
venue <- unlist(contents_level[["venues"]])
ticker <- unlist(contents_level[["tickers"]])
instance <- unlist(contents_level[["instanceId"]])
mon <- monitor(venue=venue, stock=ticker, level=first)
